---
# Zoxide Shell Integration
# Sets up zoxide for bash and fish shells

- name: "Initialize zoxide in bash with cd replacement"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.bashrc"
    line: 'eval "$(zoxide init bash --cmd cd)"'
    regexp: ".*zoxide init bash.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    create: true
    mode: '0644'

- name: "Create fish conf.d directory"
  ansible.builtin.file:
    path: "{{ target_user_home }}/.config/fish/conf.d"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0755'

- name: "Initialize zoxide in fish with cd replacement (separate conf.d file)"
  ansible.builtin.copy:
    dest: "{{ target_user_home }}/.config/fish/conf.d/zoxide.fish"
    content: |
      # Zoxide smart directory jumping with cd replacement
      # Managed by thomsible
      zoxide init fish --cmd cd | source
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0644'

- name: "Display zoxide setup info"
  ansible.builtin.debug:
    msg: "Zoxide smart directory navigation configured for bash and fish with cd replacement. Usage: cd <partial> jumps to frequently visited directories"
