services:
  debian11:
    image: debian:11
    container_name: debian11
    tty: true
    stdin_open: true
    command: ["sleep", "infinity"]
    networks:
      - thomsible

  debian12:
    image: debian:12
    container_name: debian12
    tty: true
    stdin_open: true
    command: ["sleep", "infinity"]
    networks:
      - thomsible

  ubuntu2404:
    image: ubuntu:24.04
    container_name: ubuntu2404
    tty: true
    stdin_open: true
    command: ["sleep", "infinity"]
    networks:
      - thomsible

  fedora42:
    image: fedora:42
    container_name: fedora42
    tty: true
    stdin_open: true
    command: ["sleep", "infinity"]
    networks:
      - thomsible

networks:
  thomsible:
    driver: bridge
