---
# Komplettes Setup: Ansible-Benutzer + SSH-Keys + Git für Ziel-Benutzer
- name: "Complete ansible setup with git"
  hosts: all
  become: true
  gather_facts: true
  roles:
    - thomsible_user  # Ansible-Benutzer anlegen
    - ssh_keys        # SSH für Ziel-Benutzer konfigurieren
    - git             # Git installieren und konfigurieren


