---
# Komplettes thomsible Setup: Benutzer + SSH + Shell + Git + GitHub-Tools
- name: "Complete ansible setup with all tools"
  hosts: all
  become: true
  gather_facts: true
  roles:
    - thomsible_user  # Ansible-Benutzer anlegen
    - ssh_keys        # SSH für Ziel-Benutzer konfigurieren
    - user_config     # Shell und PATH konfigurieren
    - git             # Git installieren und konfigurieren
    - github_tools    # GitHub-Tools installieren (lazygit, btop, fzf)


