---
# Komplettes Setup: Ansible-Benutzer + SSH-Keys für Ziel-Benutzer
- name: "Phase 1: Setup ansible user (as root)"
  hosts: all
  become: true
  gather_facts: true
  roles:
    - thomsible_user

- name: "Phase 2: Configure target user SSH access"
  hosts: all
  become: true
  gather_facts: false
  roles:
    - ssh_keys


