---
# Zwei-Phasen-Deployment: Erst Benutzer anlegen, dann mit diesem Benutzer arbeiten

# Phase 1: thomsible_user Rolle als root ausführen
- name: "Phase 1: Create ansible user (as root)"
  hosts: all
  become: true
  gather_facts: true
  roles:
    - thomsible_user

# Phase 2: Weitere Rollen als ansible Benutzer ausführen
- name: "Phase 2: Run additional roles (as ansible user)"
  hosts: all
  remote_user: "{{ ansible_user_name }}"
  become: false
  gather_facts: false
  tasks:
    - name: Test ansible user access
      ansible.builtin.command: whoami
      register: test_output_user
      changed_when: false

    - name: Test sudo access
      ansible.builtin.command: whoami
      become: true
      changed_when: false

    # Hier würden weitere Rollen stehen:
    # roles:
    #   - git
    #   - vim
    #   - firefox
    #   - etc.
