---
# Zwei-Phasen-Deployment: Erst Benutzer anlegen, dann mit diesem Benutzer arbeiten

# Phase 1: thomsible_user Rolle als root ausführen
- name: "Phase 1: Create thomsible user (as root)"
  hosts: all
  become: true
  gather_facts: true
  roles:
    - thomsible_user

# Phase 2: Weitere Rollen als thomsible Benutzer ausführen
- name: "Phase 2: Run additional roles (as thomsible user)"
  hosts: all
  remote_user: thomsible
  become: false
  gather_facts: false
  tasks:
    - name: Test that we are running as thomsible user
      ansible.builtin.shell: |
        echo "Current user: $(whoami)"
        echo "Home directory: $HOME"
        echo "Groups: $(groups)"
      register: test_output_user

    - name: Test that we can use sudo
      ansible.builtin.shell: |
        echo "Sudo test: $(sudo whoami)"
        echo "Sudo groups: $(sudo groups)"
      register: test_output_sudo
      become: true

    - name: Display user test results
      ansible.builtin.debug:
        var: test_output_user.stdout_lines

    - name: Display sudo test results
      ansible.builtin.debug:
        var: test_output_sudo.stdout_lines

    # Hier würden weitere Rollen stehen:
    # roles:
    #   - git
    #   - vim
    #   - firefox
    #   - etc.
