---
- name: Get target user information
  ansible.builtin.getent:
    database: passwd
    key: "{{ target_user }}"
  register: target_user_info

- name: Set target user home directory
  ansible.builtin.set_fact:
    target_user_home: "{{ target_user_info.ansible_facts.getent_passwd[target_user][4] }}"

- name: Install required packages for archive extraction
  ansible.builtin.package:
    name:
      - unzip
      - tar
      - gzip
    state: present

- name: Set GitHub tools installation path
  ansible.builtin.set_fact:
    github_tools_full_path: "{{ target_user_home }}/{{ github_tools_install_path }}"

- name: Create GitHub tools directory for target user
  ansible.builtin.file:
    path: "{{ github_tools_full_path }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'

- name: Install GitHub tools
  include_tasks: install_tool.yml
  loop: "{{ github_tools_to_install }}"
  loop_control:
    loop_var: tool_name
  vars:
    tool_config: "{{ github_tools_available[tool_name] }}"

- name: Install system tools
  ansible.builtin.include_tasks: install_system_tools.yml

- name: Setup shell aliases for tools
  ansible.builtin.include_tasks: setup_aliases.yml
  when: github_tools_create_aliases | bool
