---
# Setup shell aliases for GitHub tools
# This task creates aliases for tools that have an 'alias' configuration

- name: "Collect tools with aliases"
  ansible.builtin.set_fact:
    tools_with_aliases: >-
      {{
        github_tools_to_install |
        map('extract', github_tools_available) |
        selectattr('alias', 'defined') |
        list
      }}

- name: "Create fish config directory"
  ansible.builtin.file:
    path: "{{ target_user_home }}/.config/fish/conf.d"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0755'
  when: tools_with_aliases | length > 0

- name: "Create fish aliases file"
  ansible.builtin.template:
    src: fish_aliases.fish.j2
    dest: "{{ github_tools_fish_aliases_file }}"
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0644'
  when: tools_with_aliases | length > 0

- name: "Create bash aliases file"
  ansible.builtin.template:
    src: bash_aliases.j2
    dest: "{{ github_tools_bash_aliases_file }}"
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0644'
  when: tools_with_aliases | length > 0

- name: "Ensure bash aliases are sourced in .bashrc"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.bashrc"
    line: "[ -f ~/.bash_aliases ] && . ~/.bash_aliases"
    regexp: ".*bash_aliases.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    create: yes
  when: tools_with_aliases | length > 0

- name: "Create starship config directory"
  ansible.builtin.file:
    path: "{{ target_user_home }}/.config"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0755'
  when: "'starship' in github_tools_to_install"

- name: "Setup starship configuration"
  ansible.builtin.copy:
    src: starship.toml
    dest: "{{ target_user_home }}/.config/starship.toml"
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0644'
    backup: yes
  when: "'starship' in github_tools_to_install"

- name: "Initialize starship in bash"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.bashrc"
    line: 'eval "$(starship init bash)"'
    regexp: ".*starship init bash.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    create: yes
  when: "'starship' in github_tools_to_install"

- name: "Initialize starship in fish"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.config/fish/config.fish"
    line: 'starship init fish | source'
    regexp: ".*starship init fish.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    create: yes
  when: "'starship' in github_tools_to_install"

- name: "Initialize atuin in bash"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.bashrc"
    line: 'eval "$(atuin init bash)"'
    regexp: ".*atuin init bash.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    create: yes
  when: "'atuin' in github_tools_to_install"

- name: "Initialize atuin in fish"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.config/fish/config.fish"
    line: 'atuin init fish | source'
    regexp: ".*atuin init fish.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    create: yes
  when: "'atuin' in github_tools_to_install"

- name: "Initialize zoxide in bash with cd replacement"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.bashrc"
    line: 'eval "$(zoxide init bash --cmd cd)"'
    regexp: ".*zoxide init bash.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    create: yes
  when: "'zoxide' in github_tools_to_install"

- name: "Initialize zoxide in fish with cd replacement"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.config/fish/config.fish"
    line: 'zoxide init fish --cmd cd | source'
    regexp: ".*zoxide init fish.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    create: yes
  when: "'zoxide' in github_tools_to_install"
