---
# Setup shell aliases for GitHub tools
# This task creates aliases for tools that have an 'alias' configuration

- name: "Collect tools with aliases"
  ansible.builtin.set_fact:
    tools_with_aliases: >-
      {{
        github_tools_to_install |
        map('extract', github_tools_available) |
        selectattr('alias', 'defined') |
        list
      }}

- name: "Create fish config directory"
  ansible.builtin.file:
    path: "{{ target_user_home }}/.config/fish/conf.d"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  when: tools_with_aliases | length > 0

- name: "Create fish aliases file"
  ansible.builtin.template:
    src: fish_aliases.fish.j2
    dest: "{{ github_tools_fish_aliases_file }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0644'
  when: tools_with_aliases | length > 0

- name: "Create bash aliases file"
  ansible.builtin.template:
    src: bash_aliases.j2
    dest: "{{ github_tools_bash_aliases_file }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0644'
  when: tools_with_aliases | length > 0

- name: "Ensure bash aliases are sourced in .bashrc"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.bashrc"
    line: "[ -f ~/.bash_aliases ] && . ~/.bash_aliases"
    regexp: ".*bash_aliases.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    create: yes
  when: tools_with_aliases | length > 0

- name: "Setup starship configuration"
  ansible.builtin.template:
    src: starship.toml.j2
    dest: "{{ target_user_home }}/.config/starship.toml"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0644'
  when: "'starship' in github_tools_to_install"

- name: "Initialize starship in bash"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.bashrc"
    line: 'eval "$({{ target_user_home }}/local/bin/starship init bash)"'
    regexp: ".*starship init bash.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    create: yes
  when: "'starship' in github_tools_to_install"

- name: "Initialize starship in fish"
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.config/fish/config.fish"
    line: '{{ target_user_home }}/local/bin/starship init fish | source'
    regexp: ".*starship init fish.*"
    state: present
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    create: yes
  when: "'starship' in github_tools_to_install"
