---
# Install system tools that are not available from GitHub releases
# These tools are installed via package managers

- name: "Install system tools on Debian/Ubuntu"
  ansible.builtin.apt:
    name:
      - ncdu          # Interactive disk usage
      - lshw          # Hardware information
      - mtr           # Network tracing (traceroute + ping)
      - glances       # System monitoring
      - python3-pip   # For Python tools
      - pipx          # For Python applications
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: "Install system tools on RedHat/Fedora"
  ansible.builtin.dnf:
    name:
      - ncdu          # Interactive disk usage
      - lshw          # Hardware information
      - mtr           # Network tracing (traceroute + ping)
      - glances       # System monitoring
      - python3-pip   # For Python tools
      - pipx          # For Python applications
    state: present
  when: ansible_os_family == "RedHat"

- name: "Install Python tools via pipx"
  ansible.builtin.shell: |
    pipx install magic-wormhole
    pipx install unp
  register: pipx_install_result
  failed_when: false
  changed_when: "'already installed' not in pipx_install_result.stdout"

- name: "Display system tools installation"
  ansible.builtin.debug:
    msg: |
      📦 System Tools installiert:
      - ncdu: Interaktive Festplattenspeicher-Analyse
      - lshw: Hardware-Informationen
      - mtr: Kombiniert ping und traceroute
      - glances: System-Monitoring Dashboard
      - magic-wormhole: Sichere Dateiübertragung
      - unp: Universeller Archiv-Extraktor
