---
# Install system tools that are not available from GitHub releases
# These tools are installed via package managers

- name: "Install system tools on Debian/Ubuntu"
  ansible.builtin.apt:
    name:
      - ncdu          # Interactive disk usage
      - lshw          # Hardware information
      - mtr           # Network tracing (traceroute + ping)
      - glances       # System monitoring
      - gh            # GitHub CLI
      - python3-pip   # For Python tools
      - pipx          # For Python applications
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: "Install system tools on RedHat/Fedora"
  ansible.builtin.dnf:
    name:
      - ncdu          # Interactive disk usage
      - lshw          # Hardware information
      - mtr           # Network tracing (traceroute + ping)
      - glances       # System monitoring
      - gh            # GitHub CLI
      - python3-pip   # For Python tools
      - pipx          # For Python applications
    state: present
  when: ansible_os_family == "RedHat"

- name: "Install Python tools via pipx"
  ansible.builtin.shell: |
    pipx install unp
  register: pipx_install_result
  failed_when: false
  changed_when: "'already installed' not in pipx_install_result.stdout"

- name: "Display system tools installation"
  ansible.builtin.debug:
    msg: "System tools installed: ncdu (disk usage), lshw (hardware info), mtr (network tracing), glances (monitoring), gh (GitHub CLI), unp (archive extractor)"
