---
# Install lazygit - Terminal UI for Git
# Configuration comes from defaults/main.yml -> tools_config.lazygit

- name: "Install lazygit from GitHub"
  ansible.builtin.include_tasks: ../github_tool_install.yml
