---
# GitHub Tools Configuration
# Diese Datei definiert die verfügbaren GitHub-Tools mit ihren spezifischen Konfigurationen

github_tools_available:
  # Git Terminal UI
  lazygit:
    repo: "jesseduffield/lazygit"
    asset_pattern: ".*Linux_x86_64.tar.gz$"
    archive_extension: "tar.gz"
    description: "Terminal UI for Git"

  # System Monitor
  btop:
    repo: "aristocratos/btop"
    asset_pattern: ".*x86_64-linux-musl.tbz$"
    archive_extension: "tbz"
    description: "Modern system monitor"

  # Fuzzy Finder
  fzf:
    repo: "junegunn/fzf"
    asset_pattern: ".*linux_amd64.tar.gz$"
    archive_extension: "tar.gz"
    description: "Command-line fuzzy finder"

  # Cat with syntax highlighting
  bat:
    repo: "sharkdp/bat"
    asset_pattern: ".*x86_64-unknown-linux-gnu.tar.gz$"
    archive_extension: "tar.gz"
    description: "Cat with syntax highlighting"
    alias: "cat"  # Optional: replaces cat command

  # Modern find replacement
  fd:
    repo: "sharkdp/fd"
    asset_pattern: ".*x86_64-unknown-linux-gnu.tar.gz$"
    archive_extension: "tar.gz"
    description: "Modern find replacement"
    # No alias by default - fd is different enough from find

  # Modern ls replacement
  eza:
    repo: "eza-community/eza"
    asset_pattern: ".*x86_64-unknown-linux-gnu.tar.gz$"
    archive_extension: "tar.gz"
    description: "Modern ls replacement"
    alias: "ls"   # Optional: replaces ls command

  # Fast grep replacement (binary name is 'rg')
  ripgrep:
    repo: "BurntSushi/ripgrep"
    asset_pattern: ".*x86_64-unknown-linux-musl.tar.gz$"
    archive_extension: "tar.gz"
    binary_name: "rg"  # The actual binary name in the archive
    description: "Fast grep replacement"
    alias: "grep" # Optional: replaces grep command


  # Modern du replacement
  dust:
    repo: "bootandy/dust"
    asset_pattern: ".*x86_64-unknown-linux-musl.tar.gz$"
    archive_extension: "tar.gz"
    description: "Modern du replacement"
    alias: "du" # Optional: replaces du command

  # Modern ps replacement
  procs:
    repo: "dalance/procs"
    asset_pattern: ".*x86_64-linux.zip$"
    archive_extension: "zip"
    description: "Modern ps replacement"
    alias: "ps" # Optional: replaces ps command

  # Smart cd replacement
  zoxide:
    repo: "ajeetdsouza/zoxide"
    asset_pattern: ".*x86_64-unknown-linux-musl.tar.gz$"
    archive_extension: "tar.gz"
    description: "Smart cd replacement"
    # Note: zoxide needs shell integration, not just alias

  # Cross-shell prompt
  starship:
    repo: "starship/starship"
    asset_pattern: ".*x86_64-unknown-linux-musl.tar.gz$"
    archive_extension: "tar.gz"
    description: "Cross-shell prompt"
    # No alias - prompt enhancement

  # Magical shell history with sync
  atuin:
    repo: "atuinsh/atuin"
    asset_pattern: ".*x86_64-unknown-linux-gnu.tar.gz$"
    archive_extension: "tar.gz"
    description: "Magical shell history with sync"
    # No alias - history enhancement with sync capabilities

  # Practical command examples
  tealdeer:
    repo: "tealdeer-rs/tealdeer"
    asset_pattern: "^tealdeer-linux-x86_64-musl$"
    archive_extension: "binary"
    description: "Practical command examples"
    alias: "tldr" # Optional: tldr command

  # Modern df replacement
  duf:
    repo: "muesli/duf"
    asset_pattern: ".*linux_x86_64.tar.gz$"
    archive_extension: "tar.gz"
    description: "Modern df replacement"
    alias: "df" # Optional: replaces df command

  # Ping with graph
  gping:
    repo: "orf/gping"
    asset_pattern: "^gping-Linux-gnu-x86_64.tar.gz$"
    archive_extension: "tar.gz"
    description: "Ping with graph"
    # No alias - specialized tool

  # Modern dig replacement
  dog:
    repo: "ogham/dog"
    asset_pattern: ".*x86_64-unknown-linux-gnu.zip$"
    archive_extension: "zip"
    description: "Modern dig replacement"
    alias: "dig" # Optional: replaces dig command

  # Terminal Wireshark
  termshark:
    repo: "gcla/termshark"
    asset_pattern: ".*linux_x64.tar.gz$"
    archive_extension: "tar.gz"
    description: "Terminal Wireshark"
    # No alias - specialized tool

  # System upgrade tool
  topgrade:
    repo: "topgrade-rs/topgrade"
    asset_pattern: ".*x86_64-unknown-linux-gnu.tar.gz$"
    archive_extension: "tar.gz"
    description: "System upgrade tool"
    alias: "tg" # Alias for quick access

# Standard-Tools die installiert werden sollen (kann überschrieben werden)
github_tools_to_install:
  - lazygit
  - btop
  - fzf

# Erweiterte Tools (können durch Überschreibung von github_tools_to_install aktiviert werden)
# Alle verfügbaren GitHub Tools (17):
# github_tools_to_install: [lazygit, btop, fzf, bat, fd, eza, rg, dust, procs, zoxide, starship, atuin, tealdeer, duf, gping, dog, termshark, topgrade]
#
# Kategorien:
# - System: btop, procs, duf, dust, topgrade
# - Files: bat, fd, eza, rg
# - Navigation: fzf, zoxide
# - Development: lazygit, starship
# - Productivity: atuin, tealdeer
# - Network: gping, dog, termshark
#
# System Tools (installiert via Package Manager):
# - ncdu, lshw, mtr, glances, dstat, magic-wormhole, unp

# Alias-Konfiguration
# Wenn aktiviert, werden Shell-Aliase für Tools mit alias-Konfiguration erstellt
github_tools_create_aliases: false

# Installation path for GitHub tools (relative to target user home)
github_tools_install_path: ".local/bin"

# Konflikt-Überprüfung
# Wenn aktiviert, wird vor der Installation geprüft, ob Tools bereits via andere Quellen installiert sind
github_tools_check_conflicts: true

# Alias-Konfigurationsdateien
github_tools_bash_aliases_file: "{{ target_user_home }}/.bash_aliases"
github_tools_fish_aliases_file: "{{ target_user_home }}/.config/fish/conf.d/github_tools_aliases.fish"
