---
- name: Get target user information
  ansible.builtin.getent:
    database: passwd
    key: "{{ target_user }}"
  register: target_user_info

- name: Set target user home directory
  ansible.builtin.set_fact:
    target_user_home: "{{ target_user_info.ansible_facts.getent_passwd[target_user][4] }}"

- name: Ensure .ssh directory exists for target user
  ansible.builtin.file:
    path: "{{ target_user_home }}/.ssh"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0700'

- name: Add tbaer SSH public key to target user's authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ target_user }}"
    state: present
    key: "{{ tbaer_ssh_pubkey }}"
    comment: "tbaer key added by thomsible"

- name: Disable password authentication for target user
  ansible.builtin.user:
    name: "{{ target_user }}"
    password: '!'
  when: target_user != "root"  # Vorsicht bei root - nur wenn explizit gewünscht

