# Basic Starship Configuration (Fallback)
# This is only used if no starship.toml exists from yast dotfile sync
# Simple, clean prompt without special font requirements

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$java\
$docker_context\
$time\
$line_break\
$character"""

[username]
show_always = true
style_user = "blue bold"
style_root = "red bold"
format = '[$user]($style) '

[hostname]
ssh_only = false
style = "green bold"
format = '[@$hostname]($style) '

[directory]
style = "cyan bold"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = "git:"
style = "purple bold"
format = '[$symbol$branch]($style) '

[git_status]
style = "red bold"
format = '([$all_status$ahead_behind]($style))'

[python]
symbol = "py:"
style = "yellow bold"
format = '[$symbol$version]($style) '

[nodejs]
symbol = "node:"
style = "green bold"
format = '[$symbol$version]($style) '

[rust]
symbol = "rust:"
style = "red bold"
format = '[$symbol$version]($style) '

[golang]
symbol = "go:"
style = "cyan bold"
format = '[$symbol$version]($style) '

[java]
symbol = "java:"
style = "red bold"
format = '[$symbol$version]($style) '

[docker_context]
symbol = "docker:"
style = "blue bold"
format = '[$symbol$context]($style) '

[time]
disabled = false
time_format = "%H:%M"
style = "white bold"
format = '[$time]($style) '

[line_break]
disabled = false

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
