---
# Converge playbook for testing thomsible
- name: Test thomsible bootstrap
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    target_user: testuser
    # Extended tool config for full testing
    tools_config:
      lazygit:
        enabled: true
        description: "Terminal UI für Git"
        category: "development"
        repo: "jesseduffield/lazygit"
        asset_pattern: ".*linux_x86_64.tar.gz$"
        archive_extension: "tar.gz"
      
      starship:
        enabled: true
        description: "Cross-shell prompt"
        category: "shell"
        repo: "starship/starship"  
        asset_pattern: ".*x86_64-unknown-linux-musl.tar.gz$"
        archive_extension: "tar.gz"
      
      bat:
        enabled: true
        description: "Cat with syntax highlighting"
        category: "file_tools"
        repo: "sharkdp/bat"
        asset_pattern: ".*x86_64-unknown-linux-musl.tar.gz$"
        archive_extension: "tar.gz"
        alias: "cat"
      
  pre_tasks:
    - name: Debug tools_config
      ansible.builtin.debug:
        var: tools_config
  
  roles:
    - role: ../../roles/target_user_config
      tags: [target_user_config]
    
    - role: ../../roles/modern_tools
      tags: [modern_tools]
      vars:
        install_system_tools: true
        configure_git: true
        setup_shell_integration: true
        create_shell_aliases: true