---
# Converge playbook for testing thomsible
- name: Test thomsible bootstrap
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    target_user: testuser

    # Test deinstallation functionality with disabled tools
    tools_config:
      # Core tools for testing (enabled)
      lazygit:
        enabled: true
      starship:
        enabled: true
      bat:
        enabled: true
      eza:
        enabled: true
      fzf:
        enabled: true

      # Test deinstallation (disabled)
      dog:
        enabled: false
      termshark:
        enabled: false

      # Test new tools
      gk:
        enabled: true

    # Test system tools
    system_tools:
      gh:
        enabled: true
      ncdu:
        enabled: true
      # Test system tool deinstallation
      magic-wormhole:
        enabled: false
      
  pre_tasks:
    - name: Debug tools_config
      ansible.builtin.debug:
        var: tools_config
  
  roles:
    - role: ../../roles/target_user_config
      tags: [target_user_config]
    
    - role: ../../roles/modern_tools
      tags: [modern_tools]
      vars:
        install_system_tools: true
        configure_git: true
        setup_shell_integration: true
        create_shell_aliases: true