---
# Verify that tools are installed and working
- name: Verify thomsible installation
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Check that testuser exists
      ansible.builtin.user:
        name: testuser
      register: user_check
      
    - name: Verify user home directory
      ansible.builtin.stat:
        path: /home/testuser
      register: home_check
      
    - name: Assert user exists and has home
      ansible.builtin.assert:
        that:
          - user_check is succeeded
          - home_check.stat.exists
          - home_check.stat.isdir
        fail_msg: "Test user setup failed"
        success_msg: "Test user properly configured"

    - name: Check .local/bin directory exists
      ansible.builtin.stat:
        path: /home/testuser/.local/bin
      register: local_bin_check
      
    - name: Assert .local/bin directory
      ansible.builtin.assert:
        that:
          - local_bin_check.stat.exists
          - local_bin_check.stat.isdir
        fail_msg: ".local/bin directory missing"
        success_msg: ".local/bin directory exists"

    - name: Check enabled GitHub tools are installed
      ansible.builtin.stat:
        path: "/home/testuser/.local/bin/{{ item }}"
      register: enabled_tool_check
      loop:
        - lazygit
        - starship
        - bat
        - eza
        - fzf
        - gk

    - name: Assert enabled tools are installed
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.executable
        fail_msg: "Enabled tool {{ item.item }} not found or not executable"
        success_msg: "Enabled tool {{ item.item }} properly installed"
      loop: "{{ enabled_tool_check.results }}"

    - name: Check disabled GitHub tools are NOT installed
      ansible.builtin.stat:
        path: "/home/testuser/.local/bin/{{ item }}"
      register: disabled_tool_check
      loop:
        - dog
        - termshark

    - name: Assert disabled tools are NOT installed
      ansible.builtin.assert:
        that:
          - not item.stat.exists
        fail_msg: "Disabled tool {{ item.item }} should not be installed"
        success_msg: "Disabled tool {{ item.item }} correctly not installed"
      loop: "{{ disabled_tool_check.results }}"
      
    - name: Test tool functionality (as testuser)
      ansible.builtin.command:
        cmd: "sudo -u testuser /home/testuser/.local/bin/{{ item }} --version"
      register: version_check
      loop:
        - lazygit
        - starship
        - bat
        - eza
      changed_when: false
      failed_when: false

    - name: Assert tools are functional
      ansible.builtin.assert:
        that:
          - item.rc == 0
          - item.stdout is defined
          - item.stdout | length > 0
        fail_msg: "Tool {{ item.item }} version check failed"
        success_msg: "Tool {{ item.item }} is functional"
      loop: "{{ version_check.results }}"

    - name: Check system tools are installed
      ansible.builtin.command: "which {{ item }}"
      register: system_tool_check
      loop:
        - gh
        - ncdu
      changed_when: false
      failed_when: false

    - name: Assert system tools are functional
      ansible.builtin.assert:
        that:
          - item.rc == 0
        fail_msg: "System tool {{ item.item }} not found"
        success_msg: "System tool {{ item.item }} is installed"
      loop: "{{ system_tool_check.results }}"

    - name: Check Fish shell configuration
      ansible.builtin.stat:
        path: /home/testuser/.config/fish/config.fish
      register: fish_config_check
      
    - name: Assert Fish configuration exists
      ansible.builtin.assert:
        that:
          - fish_config_check.stat.exists
        fail_msg: "Fish configuration missing"
        success_msg: "Fish configuration exists"

    - name: Check PATH configuration in Fish
      ansible.builtin.slurp:
        src: /home/testuser/.config/fish/config.fish
      register: fish_config_content
      
    - name: Assert PATH is configured in Fish
      ansible.builtin.assert:
        that:
          - "'.local/bin' in fish_config_content.content | b64decode"
        fail_msg: "PATH not properly configured in Fish"
        success_msg: "PATH properly configured in Fish"

    - name: Display test summary
      ansible.builtin.debug:
        msg: |
          🎉 THOMSIBLE VERIFICATION COMPLETED SUCCESSFULLY!
          ✅ Test user created and configured
          ✅ .local/bin directory exists with correct permissions
          ✅ GitHub tools installed and functional: lazygit, starship, bat, eza, fzf, gk
          ✅ Disabled tools correctly NOT installed: dog, termshark
          ✅ System tools installed: gh (GitHub CLI), ncdu
          ✅ Fish shell configured with PATH
          ✅ Deinstallation functionality working correctly