---
- name: Get target user information
  ansible.builtin.getent:
    database: passwd
    key: "{{ target_user }}"
  register: target_user_info

- name: Set target user home directory and group
  ansible.builtin.set_fact:
    target_user_home: "{{ target_user_info.ansible_facts.getent_passwd[target_user][4] }}"
    target_user_group: "{{ target_user_info.ansible_facts.getent_passwd[target_user][2] }}"

- name: Get target user group name
  ansible.builtin.getent:
    database: group
    key: "{{ target_user_group }}"
  register: target_user_group_info

- name: Set target user group name
  ansible.builtin.set_fact:
    target_user_group_name: "{{ target_user_group_info.ansible_facts.getent_group.keys() | first }}"

- name: Install git package
  ansible.builtin.package:
    name: git
    state: present

- name: Check if git is already configured for target user
  ansible.builtin.stat:
    path: "{{ target_user_home }}/.gitconfig"
  register: gitconfig_exists

- name: Create basic git configuration for target user
  ansible.builtin.copy:
    dest: "{{ target_user_home }}/.gitconfig"
    content: |
      [user]
          name = {{ target_user }}
          email = {{ target_user }}@{{ ansible_hostname }}.local
      [init]
          defaultBranch = main
      [pull]
          rebase = false
      [core]
          editor = nano
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0644'
  when: not gitconfig_exists.stat.exists
