---
- name: Get target user information
  ansible.builtin.getent:
    database: passwd
    key: "{{ target_user }}"
  register: target_user_info

- name: Set target user home directory and group
  ansible.builtin.set_fact:
    target_user_home: "{{ target_user_info.ansible_facts.getent_passwd[target_user][4] }}"
    target_user_group: "{{ target_user_info.ansible_facts.getent_passwd[target_user][2] }}"

- name: Get target user group name
  ansible.builtin.getent:
    database: group
    key: "{{ target_user_group }}"
  register: target_user_group_info

- name: Set target user group name
  ansible.builtin.set_fact:
    target_user_group_name: "{{ target_user_group_info.ansible_facts.getent_group.keys() | first }}"

- name: Create config directory for target user
  ansible.builtin.file:
    path: "{{ target_user_home }}/.config"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0755'

- name: Create a sample config file for target user
  ansible.builtin.copy:
    dest: "{{ target_user_home }}/.config/ansible_managed"
    content: |
      # This file was created by ansible automation
      # Target user: {{ target_user }}
      # Managed by: {{ ansible_user_id }}
      # Date: {{ ansible_date_time.iso8601 }}
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0644'

- name: Create tools directory for target user
  ansible.builtin.file:
    path: "{{ target_user_home }}/tools"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0755'

- name: Install fish shell
  ansible.builtin.package:
    name: fish
    state: present

- name: Set fish as default shell for target user
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: /usr/bin/fish
  when: target_user != "root"  # Vorsicht bei root

- name: Create fish config directory for target user
  ansible.builtin.file:
    path: "{{ target_user_home }}/.config/fish"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0755'

- name: Add .local/bin to PATH in fish config
  ansible.builtin.copy:
    dest: "{{ target_user_home }}/.config/fish/config.fish"
    content: |
      # Add .local/bin to PATH for GitHub tools
      if test -d $HOME/.local/bin
          set -gx PATH $HOME/.local/bin $PATH
      end
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0644'

- name: Add .local/bin to PATH in bash profile
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.bashrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: yes
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0644'

- name: Add .local/bin to PATH in bash profile (alternative)
  ansible.builtin.lineinfile:
    path: "{{ target_user_home }}/.bash_profile"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: yes
    owner: "{{ target_user }}"
    group: "{{ target_user_group_name }}"
    mode: '0644'
