---
# Common task to get target user information including primary group
# This task should be included at the beginning of all target_user-aware roles

- name: Get target user information
  ansible.builtin.getent:
    database: passwd
    key: "{{ target_user }}"
  register: target_user_info

- name: Set target user home directory and group
  ansible.builtin.set_fact:
    target_user_home: "{{ target_user_info.ansible_facts.getent_passwd[target_user][4] }}"
    target_user_group: "{{ target_user_info.ansible_facts.getent_passwd[target_user][2] }}"

- name: Get target user group name
  ansible.builtin.getent:
    database: group
    key: "{{ target_user_group }}"
  register: target_user_group_info

- name: Set target user group name
  ansible.builtin.set_fact:
    target_user_group_name: "{{ target_user_group_info.ansible_facts.getent_group.keys() | first }}"

- name: Debug target user information
  ansible.builtin.debug:
    msg: |
      Target user: {{ target_user }}
      Home directory: {{ target_user_home }}
      Primary group ID: {{ target_user_group }}
      Primary group name: {{ target_user_group_name }}
  when: ansible_verbosity >= 1
