---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install sudo package if needed
  ansible.builtin.package:
    name: sudo
    state: present
  when: install_sudo_package | bool

- name: Ensure ansible user exists
  ansible.builtin.user:
    name: "{{ ansible_user_name }}"
    shell: /bin/bash
    groups: "{{ sudo_group }}"
    append: yes
    state: present

- name: Ensure .ssh directory exists for ansible user
  ansible.builtin.file:
    path: "/home/{{ ansible_user_name }}/.ssh"
    state: directory
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0700'

- name: Set authorized key for ansible user
  ansible.builtin.authorized_key:
    user: "{{ ansible_user_name }}"
    state: present
    key: "{{ ansible_user_ssh_pubkey }}"

- name: Allow ansible user passwordless sudo
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ ansible_user_name }}"
    content: "{{ ansible_user_name }} ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'

- name: Ensure ansible user cannot login with password
  ansible.builtin.user:
    name: "{{ ansible_user_name }}"
    password: '!'  # Sperrt Passwortlogin
