---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install sudo package if needed
  ansible.builtin.package:
    name: sudo
    state: present
  when: install_sudo_package | bool

- name: Ensure thomsible user exists
  ansible.builtin.user:
    name: thomsible
    shell: /bin/bash
    groups: "{{ sudo_group }}"
    append: yes
    state: present

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/thomsible/.ssh
    state: directory
    owner: thomsible
    group: thomsible
    mode: '0700'

- name: Set authorized key for thomsible
  ansible.builtin.authorized_key:
    user: thomsible
    state: present
    key: "{{ thomsible_ssh_pubkey }}"

- name: Allow thomsible passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/thomsible
    content: "thomsible ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: '0440'

- name: Ensure thomsible cannot login with password
  ansible.builtin.user:
    name: thomsible
    password: '!'  # Sperrt Passwortlogin
